// <auto-generated />
using System;
using Korp.Billing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Korp.Billing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("invoice_number_seq");

            modelBuilder.Entity("Korp.Billing.Domain.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsIssuanceInProgress")
                        .HasColumnType("boolean")
                        .HasColumnName("is_issuance_in_progress");

                    b.Property<long>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("number")
                        .HasDefaultValueSql("nextval('invoice_number_seq')");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("uq_invoices_number");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .IsDescending(true, false)
                        .HasDatabaseName("ix_invoices_created_at_utc_id");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoices_number_positive", "number > 0");

                            t.HasCheckConstraint("ck_invoices_status", "status IN ('open', 'closed')");

                            t.HasCheckConstraint("ck_invoices_status_timestamps", "(status = 'open' AND closed_at_utc IS NULL) OR (status = 'closed' AND closed_at_utc IS NOT NULL AND is_issuance_in_progress = false)");

                            t.HasCheckConstraint("ck_invoices_timestamps", "updated_at_utc >= created_at_utc AND (closed_at_utc IS NULL OR closed_at_utc >= created_at_utc)");
                        });
                });

            modelBuilder.Entity("Korp.Billing.Domain.Invoices.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_description");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_invoice_items");

                    b.HasIndex("InvoiceId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("uq_invoice_items_invoice_id_product_id");

                    b.ToTable("invoice_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_items_product_code", "product_code <> '' AND product_code = btrim(product_code) AND product_code = upper(product_code)");

                            t.HasCheckConstraint("ck_invoice_items_product_description", "product_description <> '' AND product_description = btrim(product_description)");

                            t.HasCheckConstraint("ck_invoice_items_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Korp.Billing.Domain.Issuance.InvoiceIssuanceProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("OutcomeCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("outcome_code");

                    b.Property<string>("OutcomeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("outcome_description");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_invoice_issuance_processes");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_invoice_issuance_processes_idempotency_key");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasDatabaseName("uq_invoice_issuance_processes_active_invoice")
                        .HasFilter("status IN ('pending', 'awaiting_stock')");

                    b.HasIndex("InvoiceId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_invoice_issuance_processes_invoice_id_created_at_utc");

                    b.HasIndex("Status", "UpdatedAtUtc")
                        .HasDatabaseName("ix_invoice_issuance_processes_status_updated_at_utc");

                    b.ToTable("invoice_issuance_processes", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_issuance_processes_outcome", "(status IN ('pending', 'awaiting_stock') AND finished_at_utc IS NULL AND outcome_code IS NULL AND outcome_description IS NULL) OR (status = 'completed' AND finished_at_utc IS NOT NULL AND outcome_code IS NULL AND outcome_description IS NULL) OR (status IN ('rejected', 'manual_intervention') AND finished_at_utc IS NOT NULL AND outcome_code IS NOT NULL)");

                            t.HasCheckConstraint("ck_invoice_issuance_processes_status", "status IN ('pending', 'awaiting_stock', 'completed', 'rejected', 'manual_intervention')");

                            t.HasCheckConstraint("ck_invoice_issuance_processes_timestamps", "updated_at_utc >= created_at_utc AND (finished_at_utc IS NULL OR finished_at_utc >= created_at_utc)");
                        });
                });

            modelBuilder.Entity("Korp.Billing.Infrastructure.Persistence.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("payload_hash");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("MessageId")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_inbox_messages_processed_at_utc");

                    b.ToTable("inbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_inbox_messages_schema_version", "schema_version > 0");
                        });
                });

            modelBuilder.Entity("Korp.Billing.Infrastructure.Persistence.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("PublishedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_published_at_utc");

                    b.HasIndex("NextAttemptAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("published_at_utc IS NULL");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_outbox_messages_lease_consistency", "(lock_id IS NULL) = (locked_until_utc IS NULL)");

                            t.HasCheckConstraint("ck_outbox_messages_published_lease", "published_at_utc IS NULL OR (lock_id IS NULL AND locked_until_utc IS NULL)");

                            t.HasCheckConstraint("ck_outbox_messages_schema_version", "schema_version > 0");
                        });
                });

            modelBuilder.Entity("Korp.Billing.Domain.Invoices.InvoiceItem", b =>
                {
                    b.HasOne("Korp.Billing.Domain.Invoices.Invoice", null)
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_items_invoices");
                });

            modelBuilder.Entity("Korp.Billing.Domain.Issuance.InvoiceIssuanceProcess", b =>
                {
                    b.HasOne("Korp.Billing.Domain.Invoices.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_issuance_processes_invoices");
                });

            modelBuilder.Entity("Korp.Billing.Domain.Invoices.Invoice", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
