<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Korp.Identity.Application\Korp.Identity.Application.csproj" />
    <ProjectReference Include="..\Korp.Identity.Domain\Korp.Identity.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Persistence\Migrations\**\*.cs">
      <NoWarn>$(NoWarn);IDE0161;CA1861</NoWarn>
    </Compile>
  </ItemGroup>

</Project>
